/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veritabaniprojesi;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Handler;
import javax.swing.JButton;

/**
 *
 * @author FD
 */
public class UreticiFirmaVeMusteri extends javax.swing.JFrame {

       
    /**
     * Creates new form UreticiFirmaVeMusteri
     */
    public UreticiFirmaVeMusteri() {
        super("Veritabanı Projesi");

        initComponents();
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        problem4 = new javax.swing.JButton();
        problem5 = new javax.swing.JButton();
        ButtonAnaMenuyeDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        problem4.setBackground(new java.awt.Color(204, 255, 255));
        problem4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        problem4.setForeground(new java.awt.Color(0, 153, 102));
        problem4.setText("Problem 4");
        problem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problem4ActionPerformed(evt);
            }
        });

        problem5.setBackground(new java.awt.Color(204, 255, 255));
        problem5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        problem5.setForeground(new java.awt.Color(0, 153, 102));
        problem5.setText("Problem 5-6");
        problem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problem5ActionPerformed(evt);
            }
        });

        ButtonAnaMenuyeDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonAnaMenuyeDon.setForeground(new java.awt.Color(0, 102, 102));
        ButtonAnaMenuyeDon.setText("Ana Menüye Geri Dön");
        ButtonAnaMenuyeDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnaMenuyeDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonAnaMenuyeDon)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(problem4)
                .addGap(46, 46, 46)
                .addComponent(problem5)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(ButtonAnaMenuyeDon)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(problem4)
                    .addComponent(problem5))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAnaMenuyeDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnaMenuyeDonActionPerformed
        // TODO add your handling code here:
        this.hide();
        //  ArayuzGirisEkrani frm = new ArayuzGirisEkrani();
        //  frm.setVisible(true);
    }//GEN-LAST:event_ButtonAnaMenuyeDonActionPerformed

    private void problem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problem4ActionPerformed
        // TODO add your handling code here:
        String[] args = {" "};
        Problem4.main(args);
    }//GEN-LAST:event_problem4ActionPerformed

    private void problem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problem5ActionPerformed
        // TODO add your handling code here:
        String[] args = {" "};
        Problem5.main(args);
    }//GEN-LAST:event_problem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UreticiFirmaVeMusteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UreticiFirmaVeMusteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UreticiFirmaVeMusteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UreticiFirmaVeMusteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UreticiFirmaVeMusteri().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAnaMenuyeDon;
    private javax.swing.JButton problem4;
    private javax.swing.JButton problem5;
    // End of variables declaration//GEN-END:variables
}
